inherit_from: .rubocop_todo.yml
AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/features/login_spec.rb'
    - 'spec/features/pet_spec.rb'
