# version: '3'
services:
  db:
    image: postgres:latest
    platform: linux/amd64
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_development

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    container_name: osanpo_container
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
      - chrome
    environment:
      TZ: Asia/Tokyo
      DATABASE_URL: "postgres://postgres:password@db:5432/app_development"
      RAILS_ENV: development
      SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub

  chrome:
    image: seleniarm/standalone-chromium:latest
    ports:
    - 4444:4444

volumes:
  postgres-data:
  bundle_data:
  node_modules:
